### ISSUE TITLE
The pass function in Control.Monad.Writer is mysterious and needs more explanation

### ISSUE THREAD

**Issue by ddssff** [ekmett/mtl#25] opened 2015-07-13 13:53 UTC
Its signature makes it look like the modify function in the State monad but more powerful.  Experience has shown me that it differs, but I don't understand how.

**Comment by ekmett** [comment] 2015-09-07 06:52
Closing this out as a partial duplicate of #5, but it definitely needs to be addressed.

**Closed by ekmett** 2015-09-07 06:52 UTC
